name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Versão que o Flet moderno geralmente exige

      - name: Install Dependencies
        run: |
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build APK
        run: |
          # O comando 'yes' responde automaticamente 'y' para qualquer pergunta do terminal
          yes | flet build apk --verbose
