name: Build Flet APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install Dependencies
        run: |
          pip install flet
          # Garante que o requirements.txt que criamos seja instalado[cite: 1, 2]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build APK
        run: |
          # Aceita licenças do Android e faz o build silencioso
          yes | flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-logistica
          # Este é o caminho padrão onde o Flet salva o APK gerado
          path: build/apk/app-release.apk
